#!/usr/bin/env python

def build(bld):
	version = bld.FLUTTER_VERSION
	library_name = 'flutter-%s' % (version, )
	prog = bld(features='c cshlib')
	prog.name = 'flutter'
	prog.target = library_name
	prog.source = 'flutter.vala'
	prog.includes = '..'
	prog.uselib = 'GOBJECT CLUTTER'

	# Vala packages to use
	prog.packages = 'clutter-1.0'
	


