#!/usr/bin/env python

ease_core_files = ["ease-actor.vala",
                   "ease-animated-zoom-slider.vala",
                   "ease-archiver.vala",
                   "ease-background.vala",
                   "ease-background-widget.vala",
                   "ease-cairo-actor.vala",
                   "ease-cairo-element.vala",
                   "ease-color.vala",
                   "ease-dialog-progress.vala",
                   "ease-dialogs.vala",
                   "ease-document.vala",
                   "ease-element.vala",
                   "ease-enums.vala",
                   "ease-gradient.vala",
                   "ease-html-exporter.vala",
                   "ease-icon-view.vala",
                   "ease-image-actor.vala",
                   "ease-image-element.vala",
                   "ease-image.vala",
                   "ease-init.vala",
                   "ease-iterable-models.vala",
                   "ease-layout.vala",
                   "ease-media-element.vala",
                   "ease-plugin-import-media.vala",
                   "ease-plugin-import-service.vala",
                   "ease-plugins.vala",
                   "ease-pdf-actor.vala",
                   "ease-pdf-element.vala",
                   "ease-scrolled-embed.vala",
                   "ease-scrolled-embed-window.vala",
                   "ease-serializable.vala",
                   "ease-serializer.vala",
                   "ease-shape-element.vala",
                   "ease-slide.vala",
                   "ease-temp.vala",
                   "ease-text.vala",
                   "ease-text-actor.vala",
                   "ease-text-element.vala",
                   "ease-theme.vala",
                   "ease-transitions.vala",
                   "ease-undo-actions-element.vala",
                   "ease-undo-actions-slide.vala",
                   "ease-undo-action.vala",
                   "ease-undo-controller.vala",
                   "ease-undo-item.vala",
                   "ease-undo-source.vala",
                   "ease-utilities.vala",
                   "ease-video-actor.vala",
                   "ease-video-element.vala",
                   "ease-zoom-slider.vala",
                   "sourcelist/source-base-group.vala",
                   "sourcelist/source-base-view.vala",
                   "sourcelist/source-expandable-group.vala",
                   "sourcelist/source-group.vala",
                   "sourcelist/source-item.vala",
                   "sourcelist/source-list.vala",
                   "sourcelist/source-number-item.vala",
                   "sourcelist/source-pane-view.vala",
                   "sourcelist/source-spinner-item.vala",
                   "sourcelist/source-view.vala"]

def build(bld):
  ease_core_packages = ["clutter-gst-1.0",
                        "clutter-gtk-0.10",
                        "gee-1.0",
                        "gmodule-2.0",
                        "json-glib-1.0",
                        "libarchive",
                        "poppler-glib",
                        "rest-extras-0.6",
                        "seed",
                        "unique-1.0",
                        'flutter-' + bld.env["FLUTTER_VERSION"][0]]

  version = bld.env["EASE_CORE_VERSION"][0]
  library_name = 'ease-core-' + version

  lib = bld(features='c cshlib', after='flutter')

  lib.name = "ease-core"
  lib.target = library_name
  
  lib.source = " ".join(ease_core_files)

  lib.cflags = ['-include', 'config.h', '-w', '-g']
  lib.uselib = 'GOBJECT CLUTTER GEE CLUTTERGST GMODULE LIBARCHIVE POPPLERGLIB RESTEXTRAS CLUTTERGTK JSONGLIB SEED'
  lib.packages = " ".join(ease_core_packages)
  
  lib.vapi_dirs = "../build/flutter ../vapi"
  
  lib.gir = "EaseCore-" + version



  

